version: '3.8'
services:
  db:
    image: 'timescale/timescaledb:latest-pg15'
    environment:
      - 'POSTGRES_PASSWORD=P@ssw0rd'
    ports:
      - '5432:5432'
    volumes:
      - './db/data:/var/lib/postgresql/data'